environment: minikube
serviceAccount: spark
volumes:
  - name: importer-data
    hostPath:
      path: /hazelnut-etl-importer-data
mounts:
  importer-data: /mnt/data
driver:
  cores: 1
  memory: "2g"
  javaOptions: "-Dconfig.resource=application.minikube.conf"
executor:
  instances: 4
  cores: 1
  memory: "500m"
hadoopConf:
sparkConf:
  "spark.ui.port": 4040
hostNetwork: false
imagePullPolicy: Never
userId: 1000
envVars:
  INPUT_PATH: "hazelnut-testdata"
