environment: minikube
serviceAccount: spark
envVars:
  INPUT_PATH: "/mnt/data/"
  DEBUG_SPARK_CONFIG: 6
volumes:
  - name: importer-data
    hostPath:
      path: /hazelnut-data
mounts:
  importer-data: /mnt/data
driver:
  cores: 1
  memory: "2g"
executor:
  instances: 2
  cores: 1
  memory: "1g"
hadoopConf:
sparkConf:
hostNetwork: false
imagePullPolicy: Never
userId: 0
